name: "Build cpu-only wheel and sdist"

on: workflow_dispatch


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build cpu wheels
        env:
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_SKIP: "pp* *-manylinux_i686 *-musllinux_*"
        uses: pypa/cibuildwheel@v2.19.1
      
      - uses: actions/upload-artifact@v4
        env:
          CIBW_SKIP: "pp* *-manylinux_i686"
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
