name: "Build cpu-only wheel and sdist"

on: workflow_dispatch


jobs:
  build_wheels_sdist:
    name: Build wheels and sdist on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build cpu wheels
        env:
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_SKIP: "pp* *-manylinux_i686 *-musllinux_*"
        uses: pypa/cibuildwheel@v2.19.1
        run: |
          git submodule update --init --recursive
          python -m pip install --upgrade pip numpy nanobind scipy scikit-build-core scikit-learn build
          python -m build --wheel
          python -m build --sdist
          mv dist/* wheelhouse/
