name: Build

on: workflow_dispatch


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.XGPR_PRIVATE_CLONE }}
          submodules: true
      - name: setup cuda
        run:
          git submodule update --init --recursive
          git submodule update --remote --recursive
          sudo apt-get update
          sudo apt-get install -y \
            cuda-toolkit-10-2 \
            cuda-cudart-dev-10-2 \
            cuda-nvrtc-dev-10-2

      - name: Build but don't test wheels
        env:
          CIBW_SKIP: "pp* cp36* cp37* *musllinux*"
          CIBW_BUILD_FRONTEND: "build"
        uses: pypa/cibuildwheel@v2.19.1
      
      - uses: actions/upload-artifact@v4
        env:
          CIBW_SKIP: "pp* cp36* cp37* *musllinux*"
          CIBW_BUILD_FRONTEND: "build"
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.XGPR_PRIVATE_CLONE }}
          submodules: true

      - name: Build sdist
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive
          python -m pip install --upgrade pip build wheel
          python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
