name: Build

on: workflow_dispatch


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup C/C++ Compiler
        id: setup-compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc-latest

      - name: Install cuda toolkit
        uses: Jimver/cuda-toolkit@master
        id: cuda-toolkit
        with:
          cuda: '11.0.1'
          log-file-suffix: '${{matrix.os}}.txt'

      - run: echo $GITHUB_PATH

      - run: nvcc -V

      - name: Build package
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive
          python -m pip install --upgrade pip build wheel
          python -m build --wheel
      
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build sdist
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive
          python -m pip install --upgrade pip build wheel
          python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
